export const PELICULAS_DEFAULT = 'PELICULAS_DEFAULT';
export const OBTENER_PELICULA_ESPECIFICA = 'OBTENER_PELICULA_ESPECIFICA';
export const BUSCAR_PELICULA_ESPECIFICA = 'BUSCAR_PELICULA_ESPECIFICA';
export const ID_PELICULA = 'ID_PELICULA';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';